
matrix:
  include:
    - language: Java
    - language: C
    - language: rust
      script: make

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - sudo apt-get install pkg-config -y
