name: Native Tests

on:
  workflow_call:
    secrets:
      webhook:
        required: true

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-latest
    container: openjdk:11-jdk
    steps:
      - uses: actions/checkout@v2

      - name: Build Cryptobox
        run: |
          make cryptobox

      - name: Build Native Bindings
        run: |
          make compile-native

      - name: Compile Cryptobox4j & Run Tests
        run: |
          make compile-java

      - name: Webhook to Wire
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Cryptobox4j - Test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook }}
        if: failure()
