name: Code Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  native-build:
    runs-on: ubuntu-20.04
    container: wirebot/cryptobox:latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute Tests
        run: |
          export LD_BIND_NOW=1 # see https://stackoverflow.com/a/39397405/7169288
          mvn test -DargLine="-Djava.library.path=$LD_LIBRARY_PATH";
