name: Code Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/native-tests.yml
    secrets:
      webhook: ${{ secrets.WEBHOOK_RELEASE }}

  release_docker_arm64:
    uses: ./.github/workflows/docker.yml
    needs: [ tests ]
    with:
      publish: false
      cryptobox_image: wirebot/cryptobox
      runtime_image: wirebot/runtime
      platform: linux/arm64
    secrets:
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      webhook: ${{ secrets.WEBHOOK_RELEASE }}

  release_docker_amd64:
    uses: ./.github/workflows/docker.yml
    needs: [ tests ]
    with:
      publish: false
      cryptobox_image: wirebot/cryptobox
      runtime_image: wirebot/runtime
      platform: linux/amd64
    secrets:
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      webhook: ${{ secrets.WEBHOOK_RELEASE }}
