name: Code Check

on:
  workflow_dispatch:
  pull_request:

env:
  CRYPTOBOX_IMAGE: wirebot/cryptobox
  RUNTIME_IMAGE: wirebot/runtime

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-20.04
    container: wirebot/cryptobox:latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute Tests
        run: |
          mvn test -DargLine="-Djava.library.path=$LD_LIBRARY_PATH"

      - name: Try to create package
        run: |
          mvn package -DskipTests

  docker-build:
    name: Try to build the docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # setup docker actions https://github.com/docker/build-push-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Cryptobox
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/Dockerfile
          context: .
          target: cryptobox
          tags: ${{ env.CRYPTOBOX_IMAGE }}:latest
          labels: ${{ steps.docker_meta_cryptobox.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: false

      - name: Build Runtime
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/Dockerfile
          context: .
          target: runtime
          tags: ${{ env.RUNTIME_IMAGE }}:latest
          labels: ${{ steps.docker_meta_runtime.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: false
