name: Docker Images Release

on:
  workflow_dispatch:
  schedule:
    # At 01:00 on Saturday - build and publish images each saturday at 1:00
    - cron: '0 1 * * 6'
  release:
    types: [ published ]

jobs:
  tests:
    uses: ./.github/workflows/native-tests.yml
    secrets:
      webhook: ${{ secrets.WEBHOOK_RELEASE }}

  release_docker:
    uses: ./.github/workflows/docker.yml
    needs: [ tests ]
    with:
      publish: true
      cryptobox_image: wirebot/cryptobox
      runtime_image: wirebot/runtime
      platforms: linux/amd64, linux/arm64
    secrets:
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      webhook: ${{ secrets.WEBHOOK_RELEASE }}
